minor revisions of the compiler on Shaheen.

diff --git a/installOption_WW3/ww3_install_shaheen/link b/installOption_WW3/ww3_install_shaheen/link
--- a/installOption_WW3/ww3_install_shaheen/link
+++ b/installOption_WW3/ww3_install_shaheen/link
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # --------------------------------------------------------------------------- #
 # link  : Linker script for use in make (customized for hardware and          #
 #         optimization. Note that this script will not be replaced if part    #
@@ -35,28 +35,16 @@
   echo "      Linking $prog"
   input="$*"
 
-# 1.b Internal variables - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# 1.b Get data from setup file - - - - - - - - - - - - - - - - - - - - - - - - 
 
-# The following line must not be removed: it is a switch for local install
-# so that all bin scripts point to the local wwatch3.env
-  export ww3_env=/home/x_sunr/scripps_kaust_model_wave/ww3-516/wwatch3.env
-# For manual install (without install_ww3_tar or install_ww3_svn) make sure to
-# either use the generic ww3_env or to add your own ww3_env="${my_directory}"
+  source $(dirname $0)/w3_setenv
+  main_dir=$WWATCH3_DIR
+  temp_dir=$WWATCH3_TMP
+  source=$WWATCH3_SOURCE
+  list=$WWATCH3_LIST
 
-  if [ ${WWATCH3_ENV} ]; then ww3_env="${WWATCH3_ENV}"; fi # alternate setup file
 
-# 1.c Read data from the environment file  - - - - - - - - - - - - - - - - - -
-
-  if [ -f $ww3_env ]
-  then
-    set `grep WWATCH3_DIR $ww3_env` ; shift
-    main_dir="$*"
-  else
-    echo "*** Set-up file $ww3_env not found ***"
-    exit 2
-  fi
-
-# 1.d Initial clean-up - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.c Initial clean-up - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
 
   rm -f $main_dir/exe/$prog
 
@@ -124,17 +112,6 @@
     opt="$opt -openmp"
   fi
 
-  # palm coupler archive
-  if [ "$prog" = 'ww3_shel' ] || [ "$prog" = 'ww3_multi' ] || [ "$prog" = 'ww3_sbs1' ]
-    then
-    if [ "$palm_mod" = 'yes' ]
-       then
-       comp=ar
-       opt="-rv $prog.a"
-       prog="$prog.a"
-    fi
-  fi
-
   # oasis coupler archive
   if [ "$prog" = 'ww3_shel' ] || [ "$prog" = 'ww3_multi' ] || [ "$prog" = 'ww3_sbs1' ] || \
      [ "$prog" = 'ww3_prnc' ] || [ "$prog" = 'ww3_prep' ] || [ "$prog" = 'ww3_prtide' ] || \
@@ -142,8 +119,14 @@
   then
     if [ "$oasis_mod" = 'yes' ]
     then
+      if [ -z "$(env | grep OASISDIR)" ]
+      then
+        echo ''
+        echo "[ERROR] OASISDIR is not defined"
+        exit 1
+      fi
       echo "link with oasis"
-      libs="$libs $OASISDIR/lib/libpsmile.MPI1.a $OASISDIR/lib/libmct.a $OASISDIR/lib/libmpeu.a $OASISDIR/lib/libscrip.a" ;
+      libs="$libs $OASISDIR/lib/libpsmile.MPI1.a $OASISDIR/lib/libmct.a $OASISDIR/lib/libmpeu.a $OASISDIR/lib/libscrip.a"
     fi
   fi
 
@@ -157,9 +140,37 @@
     esac
   fi
 
+  # parmetis library 
+  if [ "$prog" = 'ww3_shel' ] || [ "$prog" = 'ww3_multi' ] || [ "$prog" = 'ww3_sbs1' ] 
+  then
+    if [ "$pdlib_mod" = 'yes' ]
+    then
+      if [ -z "$(env | grep METIS_PATH)" ]
+      then
+        echo ''
+        echo "[ERROR] METIS_PATH is not defined"
+        exit 1
+      fi
+      echo "link with parmetis" 
+      libs="$libs $METIS_PATH/lib/libparmetis.a $METIS_PATH/lib/libmetis.a"
+    fi
+  fi
+
+  opt="$opt $EXTRA_LINK_OPTIONS"
+
 # 3.b Link
 
-  $comp $opt $objects $libs                         > link.out 2> link.err
+  rprfx="-Wl,-rpath,"
+  rpath=
+  for path in $libs
+  do
+    if [ "${path:0:2}" = '-L' ]
+    then
+      rpath="$rpath ${rprfx}${path//-L/}"
+    fi
+  done
+
+  $comp $opt $objects $libs $rpath                  > link.out 2> link.err
   OK="$?"
 
 # --------------------------------------------------------------------------- #
